/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LabTest } from "./LabTest";
import { LabTestCountArgs } from "./LabTestCountArgs";
import { LabTestFindManyArgs } from "./LabTestFindManyArgs";
import { LabTestFindUniqueArgs } from "./LabTestFindUniqueArgs";
import { DeleteLabTestArgs } from "./DeleteLabTestArgs";
import { LabTestService } from "../labTest.service";
@graphql.Resolver(() => LabTest)
export class LabTestResolverBase {
  constructor(protected readonly service: LabTestService) {}

  async _labTestsMeta(
    @graphql.Args() args: LabTestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LabTest])
  async labTests(
    @graphql.Args() args: LabTestFindManyArgs
  ): Promise<LabTest[]> {
    return this.service.labTests(args);
  }

  @graphql.Query(() => LabTest, { nullable: true })
  async labTest(
    @graphql.Args() args: LabTestFindUniqueArgs
  ): Promise<LabTest | null> {
    const result = await this.service.labTest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LabTest)
  async deleteLabTest(
    @graphql.Args() args: DeleteLabTestArgs
  ): Promise<LabTest | null> {
    try {
      return await this.service.deleteLabTest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
